# Generated by Django 2.0.5 on 2018-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='camisetas')),
                ('color', models.CharField(choices=[('black', 'Negro'), ('white', 'Blanco'), ('gray', 'Gris'), ('blue_dark', 'Azul Oscuro'), ('blue_light', 'Azul Claro'), ('red', 'Rojo'), ('green', 'Verde')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=2)),
                ('type', models.CharField(choices=[('neck_v', 'Cuello en V'), ('neck_round', 'Cuello Redondo')], max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('url', models.SlugField(max_length=80)),
                ('image', models.ManyToManyField(to='home.Images')),
            ],
        ),
    ]
