# Generated by Django 2.0.5 on 2018-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180523_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='sex',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=2),
            preserve_default=False,
        ),
    ]
