# Generated by Django 2.0.5 on 2018-05-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shirt_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='url',
            new_name='slug',
        ),
    ]
