# Generated by Django 2.0.5 on 2018-05-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180529_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Pagad'), ('received', 'Recibido'), ('in-process', 'En Proceso'), ('cancel', 'Cancelado'), ('sent', 'Enviado')], max_length=20)),
                ('total', models.IntegerField()),
                ('iva', models.CharField(default='0', max_length=10)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShirtColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Negro'), ('white', 'Blanco'), ('gray', 'Gris'), ('blue_dark', 'Azul Oscuro'), ('blue_light', 'Azul Claro'), ('red', 'Rojo'), ('green', 'Verde')], max_length=20)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shirt')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='home.ShirtColor'),
        ),
    ]
