# Generated by Django 2.0.5 on 2018-05-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180531_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Negro'), ('white', 'Blanco'), ('gray', 'Gris'), ('blue_dark', 'Azul Oscuro'), ('blue_light', 'Azul Claro'), ('red', 'Rojo'), ('green', 'Verde')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shirt')),
            ],
        ),
        migrations.RemoveField(
            model_name='shirtcolor',
            name='shirt',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='home.ShirtOrder'),
        ),
        migrations.DeleteModel(
            name='ShirtColor',
        ),
    ]
