# Generated by Django 2.0.5 on 2018-05-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180531_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShirtOrder',
            new_name='ShirtColor',
        ),
    ]
