# Generated by Django 2.0.5 on 2018-05-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180531_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtcolor',
            name='quantity',
        ),
    ]
