# Generated by Django 2.0.5 on 2018-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180531_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
    ]
