# Generated by Django 2.0.5 on 2018-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirtorder',
            name='size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
